# Generated by Django 4.0.5 on 2022-06-09 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_guest', models.IntegerField(max_length=150)),
                ('user_time', models.DateTimeField(max_length=255)),
                ('user_budget', models.IntegerField(max_length=255)),
                ('user_venue', models.CharField(max_length=255)),
                ('user_phone', models.IntegerField(max_length=255)),
                ('user_event', models.CharField(max_length=255)),
                ('user_discription', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
