# Generated by Django 4.0.4 on 2022-06-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evantapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='user_food',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermember',
            name='user_budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='user_guest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='user_phone',
            field=models.IntegerField(),
        ),
    ]
