# Generated by Django 4.0.5 on 2022-06-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evantapp', '0002_usermember_user_food_alter_usermember_user_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember',
            name='user_food',
        ),
    ]
