# Generated by Django 4.0.5 on 2022-06-09 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evantapp', '0005_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='user_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
