# Generated by Django 4.0.5 on 2022-06-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evantapp', '0006_alter_reg_user_alter_usermember_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
