# Generated by Django 4.0.4 on 2022-06-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evantapp', '0008_usermember1_remove_usermember_user_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember1',
            name='status_info',
            field=models.BooleanField(default=False),
        ),
    ]
