# Generated by Django 4.0.4 on 2022-06-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evantapp', '0009_usermember1_status_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember1',
            name='status_info',
        ),
        migrations.AddField(
            model_name='usermember1',
            name='status',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
