# Generated by Django 4.0.4 on 2022-06-10 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evantapp', '0010_remove_usermember1_status_info_usermember1_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember1',
            name='user_name',
        ),
        migrations.AddField(
            model_name='usermember1',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
